export default {
  LOGIN_ATTEMPT: 'LOGIN_ATTEMPT',
  LOGIN_REDIRECT: 'LOGIN_REDIRECT',
  LOGIN_ERROR: 'LOGIN_ERROR',
  ADD_PROJECT: 'ADD_PROJECT',
  REMOVE_PROJECT: 'REMOVE_PROJECT',
  FETCH_PROJECTS: 'FETCH_PROJECTS',
  UPDATE_WEEKS: 'UPDATE_WEEKS',
  SAVE_TO_SERVER: 'SAVE_TO_SERVER',
  GET_RESOURCES: 'GET_RESOURCES',
  SET_RESOURCES: 'SET_RESOURCES',
  SET_PROJECTS: 'SET_PROJECTS',
  SAVE_SUCCESS: 'SAVE_SUCCESS',
  API_ERROR: 'API_ERROR',
  SAVE_ERROR: 'SAVE_ERROR',
  UPDATE_RESOURCE_VALUE: 'UPDATE_RESOURCE_VALUE',
  PROJECT_UUID_TO_ID_UPDATE: 'PROJECT_UUID_TO_ID_UPDATE'
}
