export default {
  LOGIN_ATTEMPT: 'LOGIN_ATTEMPT',
  LOGIN_REDIRECT: 'LOGIN_REDIRECT',
  LOGIN_ERROR: 'LOGIN_ERROR',
  ADD_PROJECT: 'ADD_PROJECT',
  REMOVE_PROJECT: 'REMOVE_PROJECT',
  SAVE_TO_SERVER: 'SAVE_TO_SERVER'
}
