export default {
  LOGIN_ATTEMPT: 'LOGIN_ATTEMPT',
  LOGIN_REDIRECT: 'LOGIN_REDIRECT',
  LOGIN_ERROR: 'LOGIN_ERROR',
  ADD_PROJECT: 'ADD_PROJECT',
  REMOVE_PROJECT: 'REMOVE_PROJECT',
  ADD_HOURS: 'ADD_HOURS',
  REMOVE_HOURS: 'REMOVE_HOURS'
}
