service: sf-project-planner

plugins:
    - serverless-webpack
    - serverless-secrets-plugin

provider:
    name: aws
    runtime: nodejs4.3
    stage: dev
    environment:
        JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
        SF_USERNAME: ${self:custom.secrets.SF_USERNAME}
        SF_PASSWORD: ${self:custom.secrets.SF_PASSWORD}
        SF_TOKEN: ${self:custom.secrets.SF_TOKEN}
        SF_ENDPOINT: ${self:custom.secrets.SF_ENDPOINT}

custom:
    secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}
    webpackIncludeModules: true

functions:
    authenticate:
        handler: handler._authorizer
    login:
        handler: handler._login
        events:
            - http:
                path: login
                method: post
                integration: lambda
                cors: true
    forgotpassword:
        handler: handler._forgotPassword
        events:
            - http:
                path: forgotpassword
                method: post
                integration: lambda
                cors: true
    changePassword:
        handler: handler._changePassword
        events:
            - http:
                path: changepassword
                method: post
                integration: lambda
                authorizer: authenticate
                cors: true
    resources:
        handler: handler._resources
        events:
            - http:
                path: resources
                method: get
                integration: lambda
                authorizer: authenticate
                cors: true
            - http:
                path: resources
                method: post
                integration: lambda
                authorizer: authenticate
                cors: true
    projects:
        handler: handler._projects
        events:
            - http:
                path: projects
                method: get
                integration: lambda
                authorizer: authenticate
                cors: true
