service: sf-project-planner

plugins:
    - serverless-webpack
    - serverless-dynamodb-local

custom:
    webpackIncludeModules: true
    dynamodb:
        start:
            port: 8000
            inMemory: true
            migration: true
        migration:
            dir: ./db/migrations

provider:
    name: aws
    runtime: nodejs4.3
    stage: dev
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "dynamodb:*"
          Resource:
              - "arn:aws:dynamodb:us-east-1:*"

functions:
    authenticate:
        handler: auth.authenticate
    login:
        handler: auth.login
        events:
            - http:
                path: login
                method: post
                integration: lambda
                cors: true
    resources:
        handler: resources.default
        events:
            - http:
                path: resources
                method: get
                integration: lambda
                authorizer: authenticate
                cors: true
            - http:
                path: resources
                method: post
                integration: lambda
                authorizer: authenticate
                cors: true
    projects:
        handler: projects.hello
        events:
            - http:
                path: projects
                method: get
                integration: lambda
                authorizer: authenticate
                cors: true
